version: 2.1

orbs:
  windows: circleci/windows@5.0.0

parameters:
  maven_version: 
    default: "3.9.2"
    type: string

commands:
  set-up-env:
    steps:
      - run:
          name: save checksum of Choco lib
          command: ls -laR c:/ProgramData/chocolatey/lib > choco_lib_checksum
      - restore_cache:
          name: restore choco lib
          keys:
            - v6-choco-{{ checksum "choco_lib_checksum"}}
            - v6-choco-
      - restore_cache:
          name: restore maven cache
          keys: 
            - v5-{{ checksum "pom.xml" }}
            - v5-
      - run: 
          name: set path
          command: |
            echo 'export PATH=/c/ProgramData/chocolatey/lib/maven/apache-maven-<< pipeline.parameters.maven_version >>/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV
      - run:
            name: check maven is installed
            command: mvn --version

  save-caches:
    steps:
      - save_cache:
          paths:
            - ../.m2
          key: v5-{{ checksum "pom.xml" }}
      - save_cache:
          paths:
            - "c:/ProgramData/chocolatey/lib/maven"
            - "c:/ProgramData/chocolatey/lib/instchoco"
          key: v6-choco-{{ checksum "choco_lib_checksum"}}

jobs:
  build:
    executor:
      name: windows/default
      shell: bash
      size: medium
    steps:
      - checkout
      - run: 
          name: list lib packages
          command: ls -la C:/ProgramData/chocolatey/lib
      - set-up-env
      - run: 
          name: list lib packages after cache
          command: ls -la C:/ProgramData/chocolatey/lib | grep -e maven -e instchoco
      # - run:
      #     name: install instchoco
      #     command: choco install instchoco -y
      # - run:
      #     name: check instchoco
      #     command: instchoco -info
      - run: 
          name: package the app
          command: mvn package
      - save-caches

  test:
    executor:
      name: windows/default
      shell: bash
    parallelism: 2
    steps:
      - checkout
      - set-up-env  
      - run: 
          name: split tests
          environment:
            PARAM_TEST_DIR: "src/test/java"
            PARAM_TEST_PATTERN: "**/*Test*.java"
          command: |
            mkdir -p .circleci/tests/
            # generate excluded surefire tests using provided pattern
            circleci tests glob "$PARAM_TEST_DIR"/"$PARAM_TEST_PATTERN" | \
                sed -e "s#^$PARAM_TEST_DIR/\(.*\)\.(java|kt)#\1#" | \
                tr "/" "." > .circleci/tests/surefire_classnames
            circleci tests split --split-by=timings --timings-type=classname < .circleci/tests/surefire_classnames > /tmp/this_node_tests 
            grep -xvf /tmp/this_node_tests < .circleci/tests/surefire_classnames > .circleci/tests/surefire_classnames_ignore_list 
      - run: 
          name: test the app
          command: mvn test
      - save-caches
      - store_test_results:
          path: target/surefire-reports

workflows:
  build-and-test:
    jobs:
      - build
      # - test:
      #     requires:
      #       - build